# Generated by Django 4.2.3 on 2023-08-08 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointupdate',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 8, 8, 17, 58, 22, 262566, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointupdate',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
