# Generated by Django 4.2.3 on 2023-08-08 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_pointupdate_createdat_pointupdate_updatedat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointupdate',
            name='amount',
        ),
        migrations.AddField(
            model_name='pointupdate',
            name='problem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.problem'),
            preserve_default=False,
        ),
    ]
