# Generated by Django 4.2.3 on 2023-08-08 03:28

import base.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_user_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), default=base.models.getDefaultOptions, size=8),
        ),
    ]
