# Generated by Django 4.2.3 on 2023-08-08 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_pointupdate_amount_pointupdate_problem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pointupdate',
            unique_together={('problem', 'user')},
        ),
    ]
