# Generated by Django 4.2.3 on 2023-08-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_problem_createdat_problem_updatedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='key',
            field=models.CharField(default='BtUWr1yClUXTr1kAjwjp'),
        ),
    ]
