# Generated by Django 4.2.3 on 2023-08-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_problem_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='key',
            field=models.CharField(default='f9N75LOyv79MKMYKsEWL', unique=True),
        ),
    ]
