# Generated by Django 4.2.3 on 2023-08-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_problemvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
