# Generated by Django 4.2.3 on 2023-08-09 13:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_problem_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='key',
            field=models.CharField(default='tOy4TOavq6t9EVSrBoQZ', unique=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), default=list, size=6),
        ),
    ]
