# Generated by Django 4.2.3 on 2023-08-11 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_problem_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='status',
            new_name='vote_status',
        ),
    ]
