# Generated by Django 4.2.3 on 2023-08-11 21:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_status_problem_vote_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='vote_status',
        ),
        migrations.AddField(
            model_name='problem',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='vote_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), default=list, size=None),
        ),
    ]
