# Generated by Django 4.2.3 on 2023-08-09 15:01

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_problem_key_alter_problem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='key',
            field=models.CharField(default=base.models.generate_20_string, unique=True),
        ),
    ]
