# Generated by Django 4.2.3 on 2023-08-12 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_problem_vote_status_problem_dislikes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='voters',
            field=models.ManyToManyField(blank=True, related_name='voteds', to='base.user'),
        ),
    ]
