# Generated by Django 4.2.3 on 2023-08-12 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_problem_voters'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='problemvote',
            unique_together=set(),
        ),
    ]
