# Generated by Django 4.2.4 on 2023-08-17 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_problemvote_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='vote_history',
        ),
    ]
