# Generated by Django 4.2.4 on 2023-08-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_problem_vote_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterUniqueTogether(
            name='problemvote',
            unique_together={('problem', 'user')},
        ),
    ]
