# Generated by Django 4.2.4 on 2023-08-22 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.user'),
        ),
    ]
