# Generated by Django 4.2.4 on 2023-08-22 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_problemvote_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='truepassword',
            field=models.CharField(default='a', max_length=1000),
            preserve_default=False,
        ),
    ]
