# Generated by Django 4.2.4 on 2023-08-22 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_user_truepassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='truepassword',
        ),
    ]
